from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Optional

from .fs import ensure_dir, copy_tree
from .models import CaseCreated
from .util import slugify, now_stamp, run

EVIDENCE_TEMPLATE_GIT = "https://github.com/evidence-dev/template"
DEFAULT_TEMPLATE_NAME = "default"


def _repo_root() -> Path:
    """
    CaseForge repo root.

    Assumes this file lives at:
      <repo_root>/projforge/case_scaffold.py
    """
    return Path(__file__).resolve().parent.parent


def _repo_templates_dir() -> Path:
    """Repo-local templates directory: <repo_root>/templates/"""
    return _repo_root() / "templates"


def _template_dir(template_name: str) -> Path:
    """Template directory: <repo_root>/templates/<template_name>/"""
    return _repo_templates_dir() / template_name


def _template_overlay_dir(template_name: str) -> Path:
    """Overlay directory: <repo_root>/templates/<template_name>/overlay/"""
    return _template_dir(template_name)


def _remove_path(p: Path) -> None:
    """Remove a file or directory if it exists."""
    if not p.exists():
        return
    if p.is_dir():
        shutil.rmtree(p, ignore_errors=True)
    else:
        try:
            p.unlink()
        except FileNotFoundError:
            pass


def _copy_overlay_into_case(case_root: Path, overlay_dir: Path) -> None:
    """
    Copy overlay directory contents into case_root, allowing overwrite.

    overlay_dir should mirror the case_root layout (pages/, sources/, data/, etc).
    """
    if not overlay_dir.exists():
        return

    for item in overlay_dir.iterdir():
        dest = case_root / item.name
        if item.is_dir():
            shutil.copytree(item, dest, dirs_exist_ok=True)
        else:
            ensure_dir(dest.parent)
            shutil.copy2(item, dest)


def scaffold_evidence(case_root: Path, cases_home: Path) -> str:
    """
    Populate case_root with an Evidence project.

    Preference order:
    1) Local template at: <cases_home>/evidence-templates/template/
    2) Shallow clone from: https://github.com/evidence-dev/template

    Returns:
      "local" or "git"
    """
    local_template = cases_home / "evidence-templates" / "template"
    if local_template.exists() and local_template.is_dir():
        copy_tree(local_template, case_root)
        mode = "local"
    else:
        ensure_dir(case_root.parent)
        run(["git", "clone", "--depth", "1", EVIDENCE_TEMPLATE_GIT, str(case_root)])
        mode = "git"

    _remove_path(case_root / ".git")
    _remove_path(case_root / ".vscode")
    return mode


def _strip_owned_paths(case_root: Path) -> None:
    """Remove parts of the Evidence template that ProjForge owns and replaces."""
    _remove_path(case_root / "pages")
    _remove_path(case_root / "sources")
    _remove_path(case_root / "README.md")
    _remove_path(case_root / "evidence.config.yaml")
    _remove_path(case_root / ".evidence" / "customization" / "custom-formatting.json")


def _ensure_minimal_case_files(case_root: Path, title: str) -> None:
    """Create minimal fallbacks if overlay did not provide required files."""
    pages_dir = case_root / "pages"
    if not pages_dir.exists():
        ensure_dir(pages_dir)
        (pages_dir / "index.md").write_text(
            f"# {title}\n\n"
            "This site is a case workspace generated by ProjForge.\n\n"
            "Use the left navigation to open each report section.\n",
            encoding="utf-8",
        )

    sources_case = case_root / "sources" / "case" / "connection.yaml"
    if not sources_case.exists():
        write_evidence_duckdb_source(case_root, "case")

    readme = case_root / "README.md"
    if not readme.exists():
        write_case_readme(case_root, title)

    ensure_dir(case_root / "data" / "raw")


def write_data_scaffold(case_root: Path, cases_home: Path, template_name: str) -> None:
    """
    Ensure data/raw exists and ensure per-case data/load.sql exists.

    load.sql precedence:
    1) Template overlay: templates/<template_name>/overlay/data/load.sql
    2) Template fallback: templates/<template_name>/load.sql
    3) Repo legacy: templates/load.sql
    4) Host override: <cases_home>/evidence-templates/load.sql
    5) Minimal placeholder
    """
    data_dir = case_root / "data"
    raw_dir = data_dir / "raw"
    ensure_dir(raw_dir)

    load_sql = data_dir / "load.sql"
    if load_sql.exists():
        return

    overlay_load = _template_overlay_dir(template_name) / "data" / "load.sql"
    templ_load = _template_dir(template_name) / "load.sql"
    repo_legacy = _repo_templates_dir() / "load.sql"
    host_template = cases_home / "evidence-templates" / "load.sql"

    for candidate in (overlay_load, templ_load, repo_legacy, host_template):
        if candidate.exists():
            ensure_dir(load_sql.parent)
            shutil.copy2(candidate, load_sql)
            return

    load_sql.write_text(
        "-- load.sql (case snapshot)\n"
        "-- Purpose: ingest raw CSVs from data/raw into DuckDB tables and create normalized views.\n"
        "-- This file is intentionally copied per case so the build is reproducible over time.\n"
        "--\n"
        "-- Example usage:\n"
        "--   duckdb data/case.duckdb < data/load.sql\n\n"
        "PRAGMA threads=4;\n",
        encoding="utf-8",
    )


def write_evidence_duckdb_source(case_root: Path, source_name: str = "case") -> Path:
    """Create sources/<source_name>/connection.yaml pointing at data/case.duckdb."""
    source_dir = case_root / "sources" / source_name
    ensure_dir(source_dir)

    rel_db = os.path.relpath(case_root / "data" / "case.duckdb", start=source_dir)
    conn = source_dir / "connection.yaml"

    conn.write_text(
        f"name: {source_name}\n"
        "type: duckdb\n"
        "options:\n"
        f"  filename: {rel_db}\n",
        encoding="utf-8",
    )
    return conn


def write_case_readme(case_root: Path, title: str) -> None:
    """Write README.md into the case repo if missing."""
    readme = case_root / "README.md"
    if readme.exists():
        return

    readme.write_text(
        f"# {title}\n\n"
        "This directory is a self-contained Evidence.dev project for a single case.\n\n"
        "## Quick start\n\n"
        "```sh\n"
        "npm install\n"
        "npm run dev\n"
        "```\n\n"
        "## Data workflow\n\n"
        "Place raw exports in `data/raw/`.\n\n"
        "Build or rebuild the case DuckDB:\n\n"
        "```sh\n"
        "duckdb data/case.duckdb < data/load.sql\n"
        "npm run sources\n"
        "```\n\n"
        "## Project structure\n\n"
        "- pages/ : report sections\n"
        "- sources/ : Evidence connection configs\n"
        "- data/raw/ : raw vendor exports (unchanged)\n"
        "- data/case.duckdb : case database\n"
        "- data/load.sql : per-case snapshot of loader logic\n",
        encoding="utf-8",
    )


def create_case(
    *,
    cases_home: Path,
    case_id: str,
    title: Optional[str] = None,
    template_name: str = DEFAULT_TEMPLATE_NAME,
    no_git: bool = False,
) -> CaseCreated:
    """
    Create a new case directory under cases_home.

    Behavior:
    - Scaffold Evidence base (git clone or local evidence template copy)
    - Strip ProjForge-owned paths from the scaffold
    - Apply template overlay: templates/<template_name>/overlay/ into case root
    - Ensure minimal required files exist (fallback if template incomplete)
    """
    cases_home = cases_home.expanduser().resolve()
    ensure_dir(cases_home)

    case_id = case_id.strip()
    case_title = title.strip() if title else case_id
    template_name = (template_name or DEFAULT_TEMPLATE_NAME).strip()

    slug = f"{slugify(case_id)}_{now_stamp()}"
    case_root = cases_home / slug
    if case_root.exists():
        raise RuntimeError(f"Case directory already exists: {case_root}")

    ensure_dir(case_root)

    scaffold_mode = "none"
    if not no_git:
        scaffold_mode = scaffold_evidence(case_root, cases_home)

    _strip_owned_paths(case_root)

    template_root = _template_dir(template_name)
    _copy_overlay_into_case(case_root, template_root)

    write_data_scaffold(case_root, cases_home, template_name)
    _ensure_minimal_case_files(case_root, case_title)

    return CaseCreated(
        case_root=case_root,
        slug=slug,
        scaffold_mode=scaffold_mode,
        duckdb_path=case_root / "data" / "case.duckdb",
        connection_yaml=case_root / "sources" / "case" / "connection.yaml",
    )
