select
  ts,
  chain,
  format,
  tx_hash,
  direction,
  from_address,
  to_address,
  from_label,
  to_label,
  transfer_label,
  asset,
  amount_value,
  amount_usd_value,
  stolen_amount_value,
  stolen_amount_usd_value,
  tx_label_actions,
  tx_label_counterparty,
  tx_label_value,
  tx_label_asset,
  tx_label_status,
  tx_is_theft,
  tx_is_cross_chain,
  tx_cc_id,
  tx_cc_direction,
  cc_match_side,
  cc_match_eligible,
  source_file
from transactions
order by ts nulls last, tx_hash, direction nulls first
limit 50;
