-- Shared QA surface: rows needing review.
-- Guarantees at least one typed row for Evidence source extraction.
with actual as (
  select
    vendor,
    format,
    chain,
    ts,
    tx_hash,
    from_address,
    to_address,
    from_label,
    to_label,
    address_label,
    direction,
    asset,
    amount_value,
    amount_usd_value,
    transfer_label,
    theft_id,
    stolen_amount_value,
    source_file,
    tx_label_actions,
    tx_label_counterparty,
    tx_label_value,
    tx_label_asset,
    tx_label_status,
    from_types,
    from_counterparty,
    from_dormant_value,
    from_dormant_asset,
    from_label_status,
    to_types,
    to_counterparty,
    to_dormant_value,
    to_dormant_asset,
    to_label_status,
    tx_is_theft,
    tx_is_cross_chain,
    tx_cc_id,
    tx_cc_direction,
    cc_match_side,
    cc_match_eligible,
    time_status,
    amount_status,
    usd_status,
    stolen_amount_usd_value,
    cc_conflict_status,
    issue_flags,
    false as __placeholder_row
  from v_issue_rows
), placeholder as (
  select
    cast(null as varchar) as vendor,
    cast(null as varchar) as format,
    cast(null as varchar) as chain,
    cast(null as timestamp) as ts,
    cast(null as varchar) as tx_hash,
    cast(null as varchar) as from_address,
    cast(null as varchar) as to_address,
    cast(null as varchar) as from_label,
    cast(null as varchar) as to_label,
    cast(null as varchar) as address_label,
    cast(null as varchar) as direction,
    cast(null as varchar) as asset,
    cast(null as double) as amount_value,
    cast(null as double) as amount_usd_value,
    cast(null as varchar) as transfer_label,
    cast(null as integer) as theft_id,
    cast(null as double) as stolen_amount_value,
    cast(null as varchar) as source_file,
    cast(null as varchar) as tx_label_actions,
    cast(null as varchar) as tx_label_counterparty,
    cast(null as double) as tx_label_value,
    cast(null as varchar) as tx_label_asset,
    cast(null as varchar) as tx_label_status,
    cast(null as varchar) as from_types,
    cast(null as varchar) as from_counterparty,
    cast(null as double) as from_dormant_value,
    cast(null as varchar) as from_dormant_asset,
    cast(null as varchar) as from_label_status,
    cast(null as varchar) as to_types,
    cast(null as varchar) as to_counterparty,
    cast(null as double) as to_dormant_value,
    cast(null as varchar) as to_dormant_asset,
    cast(null as varchar) as to_label_status,
    cast(null as boolean) as tx_is_theft,
    cast(null as boolean) as tx_is_cross_chain,
    cast(null as integer) as tx_cc_id,
    cast(null as varchar) as tx_cc_direction,
    cast(null as varchar) as cc_match_side,
    cast(null as boolean) as cc_match_eligible,
    cast(null as varchar) as time_status,
    cast(null as varchar) as amount_status,
    cast(null as varchar) as usd_status,
    cast(null as double) as stolen_amount_usd_value,
    cast(null as varchar) as cc_conflict_status,
    cast(null as varchar) as issue_flags,
    true as __placeholder_row
)
select * from actual
union all
select * from placeholder
where not exists (select 1 from actual);
